#!/usr/bin/env bash
# Multi-boot validation executed only inside an ephemeral Debian guest.

set -Eeuo pipefail

# Generated by the cloud-init seed.
# shellcheck disable=SC1091
source /etc/dkc-vm-test.env
: "${DKC_TEST_FLAVOR:?missing test flavor}"
: "${DKC_TEST_KERNEL_RELEASE:?missing test kernel release}"
: "${DKC_TEST_PACKAGES:?missing package input directory}"
: "${DKC_TEST_SUPPORT:?missing test support mount}"
: "${DKC_TEST_RESULTS:?missing test result mount}"
: "${DKC_TEST_KSELFTEST_BUNDLE:?missing kselftest bundle}"
: "${DKC_TEST_KSELFTEST_SHA256:?missing kselftest checksum}"

case "$DKC_TEST_FLAVOR" in
v2 | v3 | v4) ;;
*)
	printf 'invalid test flavor\n' >&2
	exit 2
	;;
esac
[[ "$DKC_TEST_KERNEL_RELEASE" =~ ^[A-Za-z0-9.+~-]+-v[234]-amd64$ ]] || {
	printf 'invalid test kernel release\n' >&2
	exit 2
}
[ -d "$DKC_TEST_PACKAGES" ]
[ -d "$DKC_TEST_SUPPORT" ]
[ -f "$DKC_TEST_SUPPORT/packages.sha256" ]
[ -d "$DKC_TEST_RESULTS" ]
[ -f "$DKC_TEST_KSELFTEST_BUNDLE" ]
[ -f "$DKC_TEST_KSELFTEST_SHA256" ]

selector=/usr/local/bin/dkc-cpu-select
state_dir=/var/lib/dkc-vm-test
stage_file="${state_dir}/stage"
stock_file="${state_dir}/stock-kernel"
mkdir -p "$state_dir" "$DKC_TEST_RESULTS"

stage="$(cat "$stage_file" 2>/dev/null || printf bootstrap)"

event() {
	local line
	line="DKC_VM_EVENT time=$(date -u +%Y-%m-%dT%H:%M:%SZ) flavor=${DKC_TEST_FLAVOR} stage=${stage} $*"
	printf '%s\n' "$line" >>"${DKC_TEST_RESULTS}/events.log"
	printf '%s\n' "$line" >/dev/ttyS0
}

write_result() {
	local status="$1" qualification=NOT_RUN
	if [ -f "${DKC_TEST_RESULTS}/kselftest-summary.env" ] &&
		grep -qx 'status=PASS' "${DKC_TEST_RESULTS}/kselftest-summary.env"; then
		qualification=PASS
	fi
	cat >"${DKC_TEST_RESULTS}/result.env" <<EOF
status=${status}
flavor=${DKC_TEST_FLAVOR}
target_kernel=${DKC_TEST_KERNEL_RELEASE}
stock_kernel=$(cat "$stock_file" 2>/dev/null || printf unknown)
final_stage=${stage}
qualification=${qualification}
EOF
}

on_error() {
	local rc=$? line="$1"
	trap - ERR
	set +e
	event "status=FAIL line=${line} rc=${rc}"
	write_result FAIL
	for log in "${DKC_TEST_RESULTS}"/*.log; do
		[ -f "$log" ] || continue
		tail -n 80 "$log" >>"${DKC_TEST_RESULTS}/failure-tail.log"
	done
	sync
	systemctl poweroff --no-block
	sleep 20
	exit "$rc"
}
trap 'on_error "$LINENO"' ERR

cpu_positive() {
	local where="$1" recommended
	"$selector" --json --require "$DKC_TEST_FLAVOR" >"${DKC_TEST_RESULTS}/cpu-${where}.json"
	recommended="$("$selector" --require "$DKC_TEST_FLAVOR")"
	[ "$recommended" = "$DKC_TEST_FLAVOR" ]
}

cpu_negative() {
	local requested="$1"
	local output="${DKC_TEST_RESULTS}/cpu-reject-${requested}.json"
	if "$selector" --json --require "$requested" >"$output"; then
		printf 'selector unexpectedly accepted %s on %s model\n' "$requested" "$DKC_TEST_FLAVOR" >&2
		return 1
	fi
	event "check=cpu-reject requested=${requested} status=PASS"
}

grub_selection() {
	local release="$1"
	printf 'Advanced options for Debian GNU/Linux>Debian GNU/Linux, with Linux %s\n' "$release"
}

assert_grub_entry() {
	local release="$1"
	grep -Fq "Debian GNU/Linux, with Linux ${release}" /boot/grub/grub.cfg
}

reboot_into() {
	local next_stage="$1" release="$2" selection
	selection="$(grub_selection "$release")"
	assert_grub_entry "$release"
	grub-set-default "$selection"
	grub-editenv list >"${DKC_TEST_RESULTS}/grub-environment-${stage}.txt"
	grep -Fq "saved_entry=${selection}" "${DKC_TEST_RESULTS}/grub-environment-${stage}.txt"
	printf '%s\n' "$next_stage" >"$stage_file"
	event "status=PASS next=${next_stage} kernel=${release}"
	sync
	trap - ERR
	systemctl reboot --no-block
	sleep 30
	exit 0
}

prepare_kselftest_tree() {
	local work=/var/lib/dkc-kselftest
	if [ ! -d "$work" ]; then
		mkdir -p "$work"
		(
			cd "$(dirname "$DKC_TEST_KSELFTEST_BUNDLE")"
			sha256sum --check "$(basename "$DKC_TEST_KSELFTEST_SHA256")"
		) >"${DKC_TEST_RESULTS}/kselftest-checksum.log" 2>&1
		tar --extract --xz --file="$DKC_TEST_KSELFTEST_BUNDLE" \
			--directory="$work" --no-same-owner
		chmod -R a+rX "$work"
	fi
	if find "$work" -type d ! -perm -0005 -print -quit | grep -q . ||
		find "$work" -type f ! -perm -0004 -print -quit | grep -q . ||
		find "$work" -type f -perm -0100 ! -perm -0001 -print -quit | grep -q .; then
		printf 'kselftest tree remains inaccessible to unprivileged test users\n' >&2
		return 1
	fi
	[ -x "$work/run_kselftest.sh" ]
	[ -s "$work/dkc-profile/tests.txt" ]
	[ -f "$work/dkc-profile/v3-tests.txt" ]
	[ -s "$work/dkc-profile/runtime.env" ]
}

run_kselftest_profile() {
	local work profile tests v3_tests runtime per_test aggregate expected profile_tests rc
	local logs failure_details skip_details baseline_omitted
	local outer_ok outer_skip outer_fail outer_total nested_skip plan pass raw
	local failed_name failed_log test_name
	local original_nr_open=unchanged test_nr_open hard_nofile
	local -a selectors=()
	local -A requires_v3=()
	work=/var/lib/dkc-kselftest
	profile="$work/dkc-profile"
	raw="${DKC_TEST_RESULTS}/kselftest.tap"
	logs="$work/per-test-logs"
	failure_details="${DKC_TEST_RESULTS}/kselftest-failures.log"
	skip_details="${DKC_TEST_RESULTS}/kselftest-skips.log"
	prepare_kselftest_tree
	tests="$profile/tests.txt"
	v3_tests="$profile/v3-tests.txt"
	runtime="$profile/runtime.env"
	[ -s "$tests" ] && [ -f "$v3_tests" ] && [ -s "$runtime" ]
	per_test="$(awk -F= '$1 == "per_test_timeout" {print $2}' "$runtime")"
	aggregate="$(awk -F= '$1 == "aggregate_timeout" {print $2}' "$runtime")"
	[[ "$per_test" =~ ^[1-9][0-9]*$ ]] && [ "$per_test" -le 600 ]
	[[ "$aggregate" =~ ^[1-9][0-9]*$ ]] && [ "$aggregate" -le 3600 ]
	while IFS= read -r test_name; do
		[[ "$test_name" =~ ^[A-Za-z0-9_.+-]+(/[A-Za-z0-9_.+-]+)*:[A-Za-z0-9_.+/-]+$ ]]
		grep -Fxq "$test_name" "$tests"
		requires_v3["$test_name"]=1
	done <"$v3_tests"
	[ "$(sort -u "$v3_tests" | wc -l)" -eq "${#requires_v3[@]}" ]

	expected=0
	profile_tests=0
	baseline_omitted=0
	while IFS= read -r test_name; do
		[[ "$test_name" =~ ^[A-Za-z0-9_.+-]+(/[A-Za-z0-9_.+-]+)*:[A-Za-z0-9_.+/-]+$ ]]
		profile_tests=$((profile_tests + 1))
		if [ "$DKC_TEST_FLAVOR" = v2 ] && [ -n "${requires_v3[$test_name]:-}" ]; then
			baseline_omitted=$((baseline_omitted + 1))
			continue
		fi
		selectors+=(-t "$test_name")
		expected=$((expected + 1))
	done <"$tests"
	[ "$expected" -gt 0 ]
	[ "$(sort -u "$tests" | wc -l)" -eq "$profile_tests" ]
	[ "$profile_tests" -eq "$((expected + baseline_omitted))" ]

	# These are required by selected tests and must be present in the shipped
	# modules package, not supplied by the stock kernel.
	modprobe overlay
	modprobe unix_diag
	if grep -Fxq 'core:unshare_test' "$tests"; then
		original_nr_open="$(cat /proc/sys/fs/nr_open)"
		[[ "$original_nr_open" =~ ^[1-9][0-9]*$ ]] && [ "$original_nr_open" -gt 4096 ]
		hard_nofile="$(ulimit -Hn)"
		[[ "$hard_nofile" =~ ^[1-9][0-9]*$ ]]
		[ "$hard_nofile" -gt 4096 ]
		[ "$hard_nofile" -le "$original_nr_open" ]
		# Keep fs.nr_open consistent with the inherited hard limit.  Lowering it
		# below that limit makes otherwise valid setrlimit() calls fail, while
		# leaving the image default unchanged makes unshare_test allocate a file
		# descriptor table with roughly one billion entries.
		test_nr_open="$hard_nofile"
		printf '%s\n' "$test_nr_open" >/proc/sys/fs/nr_open
		cat >"${DKC_TEST_RESULTS}/kselftest-nr-open.env" <<EOF
original=${original_nr_open}
temporary=${test_nr_open}
hard_rlimit_nofile=${hard_nofile}
restored=pending
EOF
	fi
	# A nonzero framework status is data to summarize, not an immediate ERR-trap
	# event.  Keep each test's detailed output separately so a failed CI run is
	# diagnosable without retaining a VM disk or an unbounded serial log.
	if timeout --signal=TERM --kill-after=15s "${aggregate}s" \
		"$work/run_kselftest.sh" -o "$per_test" -p "$logs" \
		"${selectors[@]}" >"$raw" 2>&1; then
		rc=0
	else
		rc=$?
	fi
	if [ "$original_nr_open" != unchanged ]; then
		printf '%s\n' "$original_nr_open" >/proc/sys/fs/nr_open
		[ "$(cat /proc/sys/fs/nr_open)" = "$original_nr_open" ]
		sed -i 's/^restored=pending$/restored=yes/' \
			"${DKC_TEST_RESULTS}/kselftest-nr-open.env"
	fi
	outer_ok="$(grep -Ec '^ok [0-9]+ selftests:' "$raw" || true)"
	outer_skip="$(grep -Eci '^ok [0-9]+ selftests:.*# (SKIP|XFAIL)' "$raw" || true)"
	outer_fail="$(grep -Ec '^not ok [0-9]+ selftests:' "$raw" || true)"
	outer_total=$((outer_ok + outer_fail))
	pass=$((outer_ok - outer_skip))
	if grep -ERh '^# ok [0-9]+ .*# (SKIP|XFAIL)' "$logs" >"$skip_details"; then
		:
	else
		: >"$skip_details"
	fi
	nested_skip="$(wc -l <"$skip_details")"
	plan="$(sed -n 's/^1[.][.]\([0-9][0-9]*\)$/\1/p' "$raw" | head -n 1)"
	cat >"${DKC_TEST_RESULTS}/kselftest-summary.env" <<EOF
status=$(if [ "$rc" -eq 0 ] && [ "$outer_fail" -eq 0 ]; then printf PASS; else printf FAIL; fi)
exit_code=${rc}
profile_tests=${profile_tests}
selected=${expected}
baseline_omitted=${baseline_omitted}
planned=${plan:-missing}
executed=${outer_total}
pass=${pass}
skip=${outer_skip}
nested_skip=${nested_skip}
fail=${outer_fail}
per_test_timeout_seconds=${per_test}
aggregate_timeout_seconds=${aggregate}
EOF
	: >"$failure_details"
	while IFS= read -r failed_name; do
		failed_name="${failed_name#*selftests: }"
		failed_name="${failed_name%% #*}"
		failed_name="${failed_name##*: }"
		failed_log="$logs/$(basename "$failed_name")"
		printf '===== %s =====\n' "$failed_name" >>"$failure_details"
		if [ -f "$failed_log" ]; then
			tail -n 120 "$failed_log" >>"$failure_details"
		else
			printf 'per-test log missing: %s\n' "$failed_log" >>"$failure_details"
		fi
	done < <(grep -E '^not ok [0-9]+ selftests:' "$raw" || true)
	tar --sort=name --create --file=- --directory="$logs" . |
		xz --threads=1 --check=sha256 -1 \
			>"${DKC_TEST_RESULTS}/kselftest-per-test-logs.tar.xz"
	(
		cd "$DKC_TEST_RESULTS"
		sha256sum kselftest-per-test-logs.tar.xz
	) >"${DKC_TEST_RESULTS}/kselftest-per-test-logs.tar.xz.sha256"
	printf '%s  kselftest.tap\n' "$(sha256sum "$raw" | awk '{print $1}')" \
		>"${DKC_TEST_RESULTS}/kselftest.tap.sha256"
	xz --threads=1 --check=sha256 -1 "$raw"
	[ "$rc" -eq 0 ]
	[ "$outer_fail" -eq 0 ]
	[ "$outer_total" -eq "$expected" ]
	[ "$plan" = "$expected" ]
	event "check=kselftest status=PASS profile=${profile_tests} selected=${expected} baseline_omitted=${baseline_omitted} pass=${pass} skip=${outer_skip} nested_skip=${nested_skip}"
}

bootstrap() {
	local stock packages package_count
	local -a package_inputs=()
	stock="$(uname -r)"
	[ "$stock" != "$DKC_TEST_KERNEL_RELEASE" ]
	[ -e "/boot/vmlinuz-${stock}" ]
	[ -d "/lib/modules/${stock}" ]
	printf '%s\n' "$stock" >"$stock_file"
	uname -a >"${DKC_TEST_RESULTS}/uname-bootstrap.txt"
	cpu_positive bootstrap
	case "$DKC_TEST_FLAVOR" in
	v2)
		cpu_negative v3
		cpu_negative v4
		;;
	v3) cpu_negative v4 ;;
	v4) ;;
	esac

	cat >/etc/apt/sources.list.d/trixie-backports.sources <<'EOF'
Types: deb
URIs: http://deb.debian.org/debian
Suites: trixie-backports
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF

	export DEBIAN_FRONTEND=noninteractive
	apt-get update >"${DKC_TEST_RESULTS}/package-bootstrap.log" 2>&1
	# Only external Debian prerequisites are resolved with APT. The DKC package
	# files below are never exposed through an APT source or passed to apt-get.
	apt-get install -y --no-install-recommends \
		clang-21 dkms initramfs-tools kmod libcap2 libcap-ng0 libelf1t64 \
		libssl3t64 linux-base lld-21 llvm-21 pahole xz-utils zlib1g \
		>>"${DKC_TEST_RESULTS}/package-bootstrap.log" 2>&1
	(
		cd "$DKC_TEST_PACKAGES"
		sha256sum --check "$DKC_TEST_SUPPORT/packages.sha256"
	) >"${DKC_TEST_RESULTS}/package-input-check.log" 2>&1
	mapfile -t package_inputs < <(find "$DKC_TEST_PACKAGES" -maxdepth 1 -type f \
		-name '*.deb' -printf '%p\n' | sort)
	[ "${#package_inputs[@]}" -eq 11 ]
	dpkg --unpack -- "${package_inputs[@]}" \
		>>"${DKC_TEST_RESULTS}/package-bootstrap.log" 2>&1
	dpkg --configure --pending \
		>>"${DKC_TEST_RESULTS}/package-bootstrap.log" 2>&1
	[ -z "$(dpkg --audit)" ]
	if find /etc/apt/sources.list.d -type f -exec grep -lF 'dkc-' {} + |
		grep -q .; then
		printf 'guest unexpectedly contains a DKC APT source\n' >&2
		return 1
	fi
	[ -s "/boot/vmlinuz-${DKC_TEST_KERNEL_RELEASE}" ]
	[ -s "/boot/initrd.img-${DKC_TEST_KERNEL_RELEASE}" ]
	[ -d "/lib/modules/${DKC_TEST_KERNEL_RELEASE}" ]
	assert_grub_entry "$DKC_TEST_KERNEL_RELEASE"
	dkms status >"${DKC_TEST_RESULTS}/dkms-bootstrap.txt"
	grep -F "$DKC_TEST_KERNEL_RELEASE" "${DKC_TEST_RESULTS}/dkms-bootstrap.txt" | grep -q installed
	modinfo -k "$DKC_TEST_KERNEL_RELEASE" -F vermagic dkc_fixture \
		>"${DKC_TEST_RESULTS}/dkms-vermagic-bootstrap.txt"
	grep -q "^${DKC_TEST_KERNEL_RELEASE} " "${DKC_TEST_RESULTS}/dkms-vermagic-bootstrap.txt"
	grep -E "^[[:space:]]*(submenu|menuentry) " /boot/grub/grub.cfg \
		>"${DKC_TEST_RESULTS}/grub-after-install.txt"
	dpkg-query -W -f='${binary:Package}\t${Version}\t${db:Status-Status}\n' 'dkc-*' \
		>"${DKC_TEST_RESULTS}/packages-after-install.tsv"
	packages="$(awk -F '\t' '$3 == "installed" {count++} END {print count+0}' \
		"${DKC_TEST_RESULTS}/packages-after-install.tsv")"
	[ "$packages" -eq 11 ]
	package_count="$(find "$DKC_TEST_PACKAGES" -maxdepth 1 -type f -name '*.deb' | wc -l)"
	[ "$package_count" -eq 11 ]
	cat >/etc/default/grub.d/99-dkc-vm-test.cfg <<'EOF'
GRUB_DEFAULT=saved
EOF
	update-grub >>"${DKC_TEST_RESULTS}/package-bootstrap.log" 2>&1
	event "check=direct-dpkg-install status=PASS packages=${packages} stock=${stock}"
	reboot_into running "$DKC_TEST_KERNEL_RELEASE"
}

running() {
	local current root_source dummy_vermagic dkms_vermagic stock
	current="$(uname -r)"
	stock="$(cat "$stock_file")"
	[ "$current" = "$DKC_TEST_KERNEL_RELEASE" ]
	uname -a >"${DKC_TEST_RESULTS}/uname-running.txt"
	cat /proc/version >"${DKC_TEST_RESULTS}/proc-version.txt"
	grep -Fq 'Debian clang version 21' "${DKC_TEST_RESULTS}/proc-version.txt"
	grep -Fq 'Debian LLD 21' "${DKC_TEST_RESULTS}/proc-version.txt"
	cpu_positive running

	root_source="$(findmnt -n -o SOURCE /)"
	[ -b "$(readlink -f "$root_source")" ]
	printf '%s\n' "$root_source" >"${DKC_TEST_RESULTS}/root-device.txt"
	[ -c /dev/ttyS0 ]
	ip route show default >"${DKC_TEST_RESULTS}/network.txt"
	[ -s "${DKC_TEST_RESULTS}/network.txt" ]
	getent ahostsv4 deb.debian.org >>"${DKC_TEST_RESULTS}/network.txt"
	[ -d "/lib/modules/${current}/kernel" ]
	[ -s "/lib/modules/${current}/modules.dep" ]

	modprobe dummy
	[ -d /sys/module/dummy ]
	dummy_vermagic="$(modinfo -k "$current" -F vermagic dummy)"
	[[ "$dummy_vermagic" == "$current "* ]]
	printf '%s\n' "$dummy_vermagic" >"${DKC_TEST_RESULTS}/dummy-vermagic.txt"

	modprobe dkc_fixture
	[ -d /sys/module/dkc_fixture ]
	dkms_vermagic="$(modinfo -k "$current" -F vermagic dkc_fixture)"
	[[ "$dkms_vermagic" == "$current "* ]]
	printf '%s\n' "$dkms_vermagic" >"${DKC_TEST_RESULTS}/dkms-vermagic-running.txt"
	dkms status >"${DKC_TEST_RESULTS}/dkms-running.txt"
	grep -F "$current" "${DKC_TEST_RESULTS}/dkms-running.txt" | grep -q installed
	run_kselftest_profile

	event "check=running-kernel status=PASS root=${root_source}"
	reboot_into cleanup "$stock"
}

cleanup() {
	local stock
	stock="$(cat "$stock_file")"
	[ "$(uname -r)" = "$stock" ]
	[ -s "/boot/vmlinuz-${stock}" ]
	assert_grub_entry "$stock"
	mapfile -t packages < <(
		dpkg-query -W -f='${binary:Package}\t${db:Status-Status}\n' 'dkc-linux-*' 2>/dev/null |
			awk -F '\t' '$2 == "installed" {print $1}' | sort -u
	)
	[ "${#packages[@]}" -gt 0 ]
	dpkg --purge -- "${packages[@]}" >"${DKC_TEST_RESULTS}/package-remove.log" 2>&1
	find /boot -maxdepth 1 -type f -printf '%f\n' | sort \
		>"${DKC_TEST_RESULTS}/boot-after-remove.txt"
	find /lib/modules -mindepth 1 -maxdepth 1 -printf '%f\n' | sort \
		>"${DKC_TEST_RESULTS}/modules-after-remove.txt"
	for removed_path in \
		"/boot/vmlinuz-${DKC_TEST_KERNEL_RELEASE}" \
		"/boot/initrd.img-${DKC_TEST_KERNEL_RELEASE}" \
		"/lib/modules/${DKC_TEST_KERNEL_RELEASE}"; do
		if [ -e "$removed_path" ]; then
			printf 'removed package path remains: %s\n' "$removed_path" >&2
			return 1
		fi
	done
	[ -s "/boot/vmlinuz-${stock}" ]
	if grep -Fq "$DKC_TEST_KERNEL_RELEASE" /boot/grub/grub.cfg; then
		printf 'removed kernel remains in GRUB configuration\n' >&2
		return 1
	fi
	dkms status >"${DKC_TEST_RESULTS}/dkms-after-remove.txt"
	if grep -Fq "$DKC_TEST_KERNEL_RELEASE" "${DKC_TEST_RESULTS}/dkms-after-remove.txt"; then
		printf 'removed kernel remains in DKMS state\n' >&2
		return 1
	fi
	dpkg-query -W -f='${binary:Package}\t${Version}\t${db:Status-Status}\n' \
		>"${DKC_TEST_RESULTS}/packages-after-remove.tsv"
	grep -E "^[[:space:]]*(submenu|menuentry) " /boot/grub/grub.cfg \
		>"${DKC_TEST_RESULTS}/grub-after-remove.txt"
	event "check=remove-and-fallback status=PASS stock=${stock}"
	stage=complete
	write_result PASS
	event "status=PASS"
	sync
	trap - ERR
	systemctl poweroff --no-block
	sleep 30
}

case "$stage" in
bootstrap) bootstrap ;;
running) running ;;
cleanup) cleanup ;;
*)
	printf 'invalid persisted test stage: %s\n' "$stage" >&2
	exit 2
	;;
esac
